name: Print Hello World

on:
  push:

jobs:
  print:
    runs-on: macos-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"

  second-job:
    runs-on: macos-latest
    steps:
      - name: Print Second Message
        run: echo "This is the second job"
