name: Print Hello World

on:
  push:

jobs:
  print:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: backend
        steps:
          - name: Repo Cloning
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: npm ci
          - name: Run test
            run: npm test
